"""Initial migration: create users, cars, and refuels tables

Revision ID: a9899424de8c
Revises: 
Create Date: 2025-09-28 21:39:45.886785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9899424de8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_car', 'cars', ['user_id', 'name'], unique=False)
    op.create_index('idx_user_default', 'cars', ['user_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_cars_user_id'), 'cars', ['user_id'], unique=False)
    op.create_table('refuels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('price_per_liter', sa.Float(), nullable=True),
    sa.Column('distance_since_last', sa.Float(), nullable=True),
    sa.Column('fuel_efficiency', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('station_name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_car_date', 'refuels', ['car_id', 'date'], unique=False)
    op.create_index('idx_car_odometer', 'refuels', ['car_id', 'odometer'], unique=False)
    op.create_index(op.f('ix_refuels_car_id'), 'refuels', ['car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refuels_car_id'), table_name='refuels')
    op.drop_index('idx_car_odometer', table_name='refuels')
    op.drop_index('idx_car_date', table_name='refuels')
    op.drop_table('refuels')
    op.drop_index(op.f('ix_cars_user_id'), table_name='cars')
    op.drop_index('idx_user_default', table_name='cars')
    op.drop_index('idx_user_car', table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
